#!/usr/bin/env python3
"""
MLX-Audio TTS generator for article audio.

Uses Kokoro model via Apple's MLX framework for fast, native Apple Silicon
speech synthesis.
"""

import argparse
import json
import time
from pathlib import Path

import numpy as np  # type: ignore
import soundfile as sf  # type: ignore


SAMPLE_RATE = 24000


import re

def normalize_text(text: str) -> str:
    """Basic whitespace normalization."""
    return " ".join((text or "").strip().split())


def sanitize_transcript(text: str) -> str:
    """
    Preserve white space and line breaks so that blocks (paragraphs, lists)
    stay distinct. This ensures Kokoro pipeline generates short, accurate
    audio segments which WhisperX can align perfectly.
    """
    if not text:
        return ""
    # Normalize internal spaces but keep newlines
    lines = [line.strip() for line in text.splitlines()]
    return "\n".join(lines).strip()


def generate_audio(transcript: str, voice: str, language_code: str, speed: float):
    """
    Generate audio using MLX-Audio Kokoro TTS and capture segments with timing.
    """
    from mlx_audio.tts.utils import load_model  # type: ignore

    started_at = time.perf_counter()
    model = load_model("mlx-community/Kokoro-82M-bf16")
    
    # We use the pipeline directly because model.generate() discards the segment text (graphemes)
    # which we need for the aligner guide.
    pipeline = model._get_pipeline(language_code)
    
    audio_segments = []
    text_segments = []
    current_samples: int = 0

    print(f"[MLX-Audio] Starting synthesis for voice={voice}, language={language_code}, speed={speed}")

    # KokoroPipeline.__call__ yields Result objects
    for result in pipeline(transcript, voice=voice, speed=speed):
        audio = result.audio
        graphemes = result.graphemes
        
        if audio is None:
            continue

        # Convert MLX array to numpy and flatten
        audio_np = np.asarray(audio, dtype=np.float32).flatten()
        seg_len = len(audio_np)
        if seg_len == 0:
            continue
            
        audio_segments.append(audio_np)

        if graphemes:
            # Map samples to time for alignment
            rate_f = float(SAMPLE_RATE)
            start_t = float(current_samples) / rate_f
            end_t = float(current_samples + seg_len) / rate_f  # type: ignore
            
            text_segments.append({
                "text": str(graphemes).strip(),
                "start": round(start_t, 3),  # type: ignore[arg-type]
                "end": round(end_t, 3)  # type: ignore[arg-type]
            })
            
        current_samples += seg_len  # type: ignore

    if not audio_segments:
        raise RuntimeError("No audio was generated by MLX-Audio.")

    combined_audio = np.concatenate(audio_segments)
    elapsed = time.perf_counter() - started_at
    total_samples = len(combined_audio)
    total_duration = float(total_samples) / float(SAMPLE_RATE)

    print(
        f"[MLX-Audio] Synthesis completed in {elapsed:.2f}s "
        f"({len(text_segments)} segments, {total_duration:.1f}s audio, RTF={elapsed / total_duration:.3f})"
    )

    return combined_audio, text_segments




def main():
    parser = argparse.ArgumentParser(
        description="Generate article audio using MLX-Audio Kokoro TTS"
    )
    parser.add_argument("--transcript-file", required=True)
    parser.add_argument("--output-audio-file", required=True)
    parser.add_argument("--output-segments-file", required=True)
    parser.add_argument("--voice", default="af_heart")
    parser.add_argument("--language-code", default="a")
    parser.add_argument("--speed", type=float, default=1.0)
    parser.add_argument(
        "--skip-alignment",
        action="store_true",
        help="Skip forced alignment (no word timestamps)",
    )
    args = parser.parse_args()

    raw_transcript = Path(args.transcript_file).read_text(encoding="utf-8").strip()
    if not raw_transcript:
        raise RuntimeError("Cannot synthesize audio from an empty transcript.")

    # Sanitize transcript for both TTS and Aligner
    transcript = sanitize_transcript(raw_transcript)
    if not transcript:
        # Fallback to normalized raw if sanitization stripped everything (unlikely)
        transcript = normalize_text(raw_transcript)

    output_audio = Path(args.output_audio_file)
    output_segments = Path(args.output_segments_file)
    output_audio.parent.mkdir(parents=True, exist_ok=True)
    output_segments.parent.mkdir(parents=True, exist_ok=True)

    total_started_at = time.perf_counter()

    # Step: Generate audio
    combined_audio, segments = generate_audio(
        transcript, args.voice, args.language_code, args.speed
    )
    sf.write(str(output_audio), combined_audio, SAMPLE_RATE)
    output_segments.write_text(json.dumps(segments, indent=2), encoding="utf-8")

    total_elapsed = time.perf_counter() - total_started_at
    print(
        f"[MLX-Audio] Total synthesis completed in {total_elapsed:.2f}s. "
        f"Audio saved to {output_audio}"
    )


if __name__ == "__main__":
    main()
